# Remova essa linha se quiser evitar o warning
# version: "3.8"

services:
  api:
    build: 
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - api-network
      - easypanel
    labels:
      - traefik.enable=true
      - traefik.docker.network=easypanel
      - traefik.http.services.api-vip.loadbalancer.server.port=8000
      - traefik.http.routers.api-vip.rule=Host(`api.seudominio.com`)
      - traefik.http.routers.api-vip.entrypoints=websecure
      - traefik.http.routers.api-vip.tls=true
      - traefik.http.routers.api-vip.tls.certresolver=letsencrypt

networks:
  api-network:
    driver: bridge
  easypanel:
    external: true
