version: "3.8"  # opcional, mas recomendado

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - api-network
      - easypanel
    labels:
      - traefik.enable=true
      - traefik.docker.network=easypanel
      - traefik.http.services.salf-api.loadbalancer.server.port=8000
      - traefik.http.routers.salf-api.entrypoints=websecure
      - traefik.http.routers.salf-api.tls=true
      - traefik.http.routers.salf-api.tls.certresolver=letsencrypt

networks:
  api-network:
    driver: bridge  # também estava escrito errado: "drive"
  easypanel:
    external: true
